#!/bin/bash
# $Id$

# Options
e=$1	# photon lab energy in GeV
thlow=$2
thup=$3
thstep=$4
#
apb=$5	# alpha + beta
amb=$6	# alpha - beta
ge1e1=$7 # gamma_e1e1
gm1m1=$8 # gamma_m1m1
ge1m2=$9 # gamma_e1m2
gm1e2=${10} # gamma_m1e2

# working dir
dirout="/dev/shm/fit-tmp/${11}"
if [[ ! -e  $dirout ]]
then
  cp -rp $Compton/fromPasquini/c/exe/compton $dirout
fi
cd $dirout
rm *.dat

# Run
rcsdrtot_2011_main <<- EOF
10
2
$apb
$amb
1
$ge1m2
$gm1m1
$ge1e1
$gm1e2
$e
$thlow
$thup
$thstep
EOF

# Output
mv *.dat output.dat
